apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-hostpath-pvc
  annotations:
    csi-hostpath-path: /var/log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath